version: '3.8'

services:
  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3001:3000"
    depends_on:
      - auth-service
  
  auth-service:
    image: python:3.12
    working_dir: /app
    volumes:
      - /opt/auth-service:/app
      - ./logs/auth-service:/app/logs 
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports: 
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://user:pass@db:3306/authdb
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=authdb
    ports:
      - "${DB_PORT}:${DB_PORT}"
  
  prometheus: #Prometheus possède prometheus-fastapi-instrumentor permettant d'exposer les métriques de l'application
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    depends_on:
      - auth-service 

  grafana:
    image: grafana/grafana:latest
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    
  node-exporter: #Si le temps ajouter node_exporter pour les infos du conteneur voir pour mettre alert manager
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"


volumes:
  db-data:
  grafana-data: